// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/v1/ldm.proto

package ldm_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteTileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tile *Tile `protobuf:"bytes,1,opt,name=tile,proto3" json:"tile,omitempty"`
}

func (x *WriteTileRequest) Reset() {
	*x = WriteTileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_ldm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteTileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTileRequest) ProtoMessage() {}

func (x *WriteTileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ldm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTileRequest.ProtoReflect.Descriptor instead.
func (*WriteTileRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ldm_proto_rawDescGZIP(), []int{0}
}

func (x *WriteTileRequest) GetTile() *Tile {
	if x != nil {
		return x.Tile
	}
	return nil
}

type WriteTileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *WriteTileResponse) Reset() {
	*x = WriteTileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_ldm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteTileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTileResponse) ProtoMessage() {}

func (x *WriteTileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ldm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTileResponse.ProtoReflect.Descriptor instead.
func (*WriteTileResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ldm_proto_rawDescGZIP(), []int{1}
}

func (x *WriteTileResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadTileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ReadTileRequest) Reset() {
	*x = ReadTileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_ldm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTileRequest) ProtoMessage() {}

func (x *ReadTileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ldm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTileRequest.ProtoReflect.Descriptor instead.
func (*ReadTileRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ldm_proto_rawDescGZIP(), []int{2}
}

func (x *ReadTileRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadTileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tile *Tile `protobuf:"bytes,2,opt,name=tile,proto3" json:"tile,omitempty"`
}

func (x *ReadTileResponse) Reset() {
	*x = ReadTileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_ldm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTileResponse) ProtoMessage() {}

func (x *ReadTileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ldm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTileResponse.ProtoReflect.Descriptor instead.
func (*ReadTileResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ldm_proto_rawDescGZIP(), []int{3}
}

func (x *ReadTileResponse) GetTile() *Tile {
	if x != nil {
		return x.Tile
	}
	return nil
}

type Tile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *Tile) Reset() {
	*x = Tile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_ldm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ldm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_api_v1_ldm_proto_rawDescGZIP(), []int{4}
}

func (x *Tile) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Tile) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_api_v1_ldm_proto protoreflect.FileDescriptor

var file_api_v1_ldm_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x64, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6c, 0x64, 0x6d, 0x2e, 0x76, 0x31, 0x22, 0x34, 0x0a, 0x10, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x04, 0x74, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c,
	0x64, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6c, 0x65,
	0x22, 0x2b, 0x0a, 0x11, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x29, 0x0a,
	0x0f, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x34, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64,
	0x54, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04,
	0x74, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x64, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6c, 0x65, 0x22, 0x34,
	0x0a, 0x04, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x32, 0xa1, 0x02, 0x0a, 0x03, 0x4c, 0x64, 0x6d, 0x12, 0x42, 0x0a, 0x09,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x6c, 0x64, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x64, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x6c,
	0x64, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x64, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x47, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x17, 0x2e, 0x6c, 0x64, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c,
	0x64, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4c, 0x0a, 0x0f, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x18, 0x2e,
	0x6c, 0x64, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x64, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x63, 0x68, 0x65, 0x6e, 0x67, 0x38, 0x35, 0x2f,
	0x67, 0x6f, 0x2d, 0x6c, 0x64, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x64, 0x6d, 0x5f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_ldm_proto_rawDescOnce sync.Once
	file_api_v1_ldm_proto_rawDescData = file_api_v1_ldm_proto_rawDesc
)

func file_api_v1_ldm_proto_rawDescGZIP() []byte {
	file_api_v1_ldm_proto_rawDescOnce.Do(func() {
		file_api_v1_ldm_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_ldm_proto_rawDescData)
	})
	return file_api_v1_ldm_proto_rawDescData
}

var file_api_v1_ldm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_ldm_proto_goTypes = []interface{}{
	(*WriteTileRequest)(nil),  // 0: ldm.v1.WriteTileRequest
	(*WriteTileResponse)(nil), // 1: ldm.v1.WriteTileResponse
	(*ReadTileRequest)(nil),   // 2: ldm.v1.ReadTileRequest
	(*ReadTileResponse)(nil),  // 3: ldm.v1.ReadTileResponse
	(*Tile)(nil),              // 4: ldm.v1.Tile
}
var file_api_v1_ldm_proto_depIdxs = []int32{
	4, // 0: ldm.v1.WriteTileRequest.tile:type_name -> ldm.v1.Tile
	4, // 1: ldm.v1.ReadTileResponse.tile:type_name -> ldm.v1.Tile
	0, // 2: ldm.v1.Ldm.WriteTile:input_type -> ldm.v1.WriteTileRequest
	2, // 3: ldm.v1.Ldm.ReadTile:input_type -> ldm.v1.ReadTileRequest
	2, // 4: ldm.v1.Ldm.ReadTileStream:input_type -> ldm.v1.ReadTileRequest
	0, // 5: ldm.v1.Ldm.WriteTileStream:input_type -> ldm.v1.WriteTileRequest
	1, // 6: ldm.v1.Ldm.WriteTile:output_type -> ldm.v1.WriteTileResponse
	3, // 7: ldm.v1.Ldm.ReadTile:output_type -> ldm.v1.ReadTileResponse
	3, // 8: ldm.v1.Ldm.ReadTileStream:output_type -> ldm.v1.ReadTileResponse
	1, // 9: ldm.v1.Ldm.WriteTileStream:output_type -> ldm.v1.WriteTileResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_ldm_proto_init() }
func file_api_v1_ldm_proto_init() {
	if File_api_v1_ldm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_ldm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteTileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_ldm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteTileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_ldm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_ldm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_ldm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_ldm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_ldm_proto_goTypes,
		DependencyIndexes: file_api_v1_ldm_proto_depIdxs,
		MessageInfos:      file_api_v1_ldm_proto_msgTypes,
	}.Build()
	File_api_v1_ldm_proto = out.File
	file_api_v1_ldm_proto_rawDesc = nil
	file_api_v1_ldm_proto_goTypes = nil
	file_api_v1_ldm_proto_depIdxs = nil
}
